route:
  receiver: default
  group_by:
    - alertname
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1h
  routes:
    - receiver: oncall-critical
      matchers:
        - severity="critical"
      group_wait: 1s
      group_interval: 5s
    - receiver: oncall-warning
      matchers:
        - severity="warning"
      group_wait: 1s
      group_interval: 5s

receivers:
  - name: default
    webhook_configs:
      - url: http://receiver:8080/default
        send_resolved: true

  - name: oncall-critical
    webhook_configs:
      - url: http://receiver:8080/oncall-critical
        send_resolved: true

  - name: oncall-warning
    webhook_configs:
      - url: http://receiver:8080/oncall-warning
        send_resolved: true
